//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FST.Web.FSTWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FSTWebService.IFSTWebService")]
    public interface IFSTWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFSTWebService/RunJob", ReplyAction="http://tempuri.org/IFSTWebService/RunJobResponse")]
        void RunJob(string recordID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFSTWebServiceChannel : FST.Web.FSTWebService.IFSTWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FSTWebServiceClient : System.ServiceModel.ClientBase<FST.Web.FSTWebService.IFSTWebService>, FST.Web.FSTWebService.IFSTWebService {
        
        public FSTWebServiceClient() {
        }
        
        public FSTWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FSTWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FSTWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FSTWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void RunJob(string recordID) {
            base.Channel.RunJob(recordID);
        }
    }
}
